---
abstract: 'OO Interface to Instagram REST API'
author:
  - 'Gabriel Vieira <gabriel.vieira@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: API-Instagram
version: 0.001
